# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a12fc151c134498431236a1785498ad110239f9c8feb75ebb991bce2e6d0684d60d640b5549c7140bde1af5e18069ab505852f976e20151b0511afffe8d9d36

test:
  secret_key_base: 2e8fa44dee3c119fb21c5b59de925fdcd776fe2504949cc61bb26fd808cf536ba160a6293efff4537a968254d269da482fff6e74e85c75d4f3933a280197ea43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
